### ISSUE TITLE
Hello!Could you please give me a gt_file?

### ISSUE THREAD

**Issue by cuienjiecv** [doubledaibo/drnet_cvpr2017#5]
I am very interested in your work.But I can't write the script file now, can you give me a copy?Thank you very much!@doubledaibo

**Comment by aviziskind** [comment]
I'm also interested in this. Can you please outline how you generated the gt_file, or upload a copy?

**Comment by pyupya** [comment]
Me either, interested in it.  Can I get gt_file, or how can I generate it?

**Comment by aviziskind** [comment]
I wrote this script to generate the ground truth file, which might be helpful to others. The ground-truth files are also included in the attached zip file.

[drnet_gt_script_and_files.zip](https://github.com/doubledaibo/drnet_cvpr2017/files/1709627/drnet_gt_script_and_files.zip)

**Comment by doubledaibo** [comment]
@aviziskind Thanks.

**Comment by chensonglu** [comment]
@aviziskind Thank you. But in line 76 of your python code, it should be "label_r_idx = predicate_LUT[rel_s['predicate']]" instead of "label_r_idx = predicate_LUT[rel_s['predicate']] + 1"? According to prepare_data.py, predicates should be 0~69 and object should be 0~100 because the background belong to 0 class. Am i right? @doubledaibo @aviziskind

**Comment by chensonglu** [comment]
@aviziskind Thank you. I verify my thought by training the model and the results show it should be "label_r_idx = predicate_LUT[rel_s['predicate']]". Thank you anyway.
